### ISSUE TITLE
Naprawa liczenia czasu od ostatniej zmiany statusu w wersji Websocket.

### ISSUE THREAD

**Issue by mkapiczy** [bms-devs/hackathon-heroku-app#14]
Po wdrożeniu wersji websocket'owej licznik zeruje się co 30s. Nie wiem jeszcze z czego to wynika, jak testowałem lokalnie było ok.

**Comment by wieczorekm** [comment]
Z tego co pamiętam to Raspberry (gdy nie zmienia się stan toalety) strzela do aplikacji co 30s. Może gdzieś tu jest problem
